// Generated by FlutterFire CLI for the shoplens2026-dev Firebase project
// (project ID: project-b1a5dd5a-69e6-4db3-9d7, project number: 115535290381)
//
// Android/iOS options support compile-time overrides via --dart-define-from-file
// (e.g. .dart_define/cookshop-dev.json). Defaults below point to shoplens2026-dev.
// Web options already use String.fromEnvironment and are unchanged.
//
// NOTE: Web API key and App ID must be filled in from Firebase Console →
// Project Settings → Your apps → Web app. Update FIREBASE_WEB_API_KEY and
// FIREBASE_WEB_APP_ID defaultValues below, or pass them via --dart-define.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web; // fallback for Windows/macOS desktop dev
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY',
        defaultValue: 'AIzaSyCOkQM8Da81NozVd3P91RjYCnaVoRsD-hw'),
    appId: String.fromEnvironment('FIREBASE_ANDROID_APP_ID',
        defaultValue: '1:115535290381:android:a69e0d2e5c92081298b544'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '115535290381'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'project-b1a5dd5a-69e6-4db3-9d7'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'project-b1a5dd5a-69e6-4db3-9d7.firebasestorage.app'),
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY',
        defaultValue: 'AIzaSyBja9-s_j6D_eogtLAfSJdaWYvoiDjWBeE'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID',
        defaultValue: '1:115535290381:ios:8b1cd372db43caec98b544'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '115535290381'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'project-b1a5dd5a-69e6-4db3-9d7'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'project-b1a5dd5a-69e6-4db3-9d7.firebasestorage.app'),
    iosBundleId: String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID',
        defaultValue: 'com.shoplens.app'),
  );
  // Web values: obtain from Firebase Console → Project Settings → Your apps → Web app.
  // Replace FILL_IN_* placeholders with real values, or pass via --dart-define.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY',
        defaultValue: 'AIzaSyBj8i4zQQubbwMCXiAbN8rphiRb9qTmt9s'),
    appId: String.fromEnvironment('FIREBASE_WEB_APP_ID',
        defaultValue: '1:115535290381:web:2874f83aa9285e2698b544'),
    messagingSenderId: String.fromEnvironment(
        'FIREBASE_WEB_MESSAGING_SENDER_ID',
        defaultValue: '115535290381'),
    projectId: String.fromEnvironment('FIREBASE_WEB_PROJECT_ID',
        defaultValue: 'project-b1a5dd5a-69e6-4db3-9d7'),
    storageBucket: String.fromEnvironment('FIREBASE_WEB_STORAGE_BUCKET',
        defaultValue: 'project-b1a5dd5a-69e6-4db3-9d7.firebasestorage.app'),
    authDomain: String.fromEnvironment('FIREBASE_WEB_AUTH_DOMAIN',
        defaultValue: 'project-b1a5dd5a-69e6-4db3-9d7.firebaseapp.com'),
    measurementId: 'G-BZMQC5XVCV',
  );
}
