// Generated by FlutterFire CLI for the shoplens-dev-499700 Firebase project
// (the real project — "shoplens-dev-prj" referenced elsewhere never existed).
//
// Android/iOS options support compile-time overrides via --dart-define-from-file
// (e.g. .dart_define/cookshop-dev.json). Defaults below point to shoplens-dev-499700.
// Web options already used String.fromEnvironment and are unchanged.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web; // fallback for Windows/macOS desktop dev
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY',
        defaultValue: 'AIzaSyBovKs-EV8FiNoNuGYidTX90J5Dxgx-meQ'),
    appId: String.fromEnvironment('FIREBASE_ANDROID_APP_ID',
        defaultValue: '1:935092313069:android:86ea0aa6e5b4ac2318a5e4'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '935092313069'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'shoplens-dev-499700'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'shoplens-dev-499700.firebasestorage.app'),
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY',
        defaultValue: 'AIzaSyCUZ4hbWyUkvduDCM0OreCZDM3B1yj9Npg'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID',
        defaultValue: '1:935092313069:ios:523bea5e851d2cd718a5e4'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '935092313069'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'shoplens-dev-499700'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'shoplens-dev-499700.firebasestorage.app'),
    iosBundleId: String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID',
        defaultValue: 'com.shoplens.app'),
  );
  // Defaults below are the dev Firebase project (shoplens-dev-499700),
  // used for local development and dev/preview builds. The prod build
  // overrides these via --dart-define in deploy-firebase.yml so the prod
  // Firebase Hosting site (shoplens-dev-499700) talks to the dev Firebase
  // project instead of dev.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY',
        defaultValue: 'AIzaSyDNo2wAuz-KHiHlQaf0OzZY-a_TWLVtTFo'),
    appId: String.fromEnvironment('FIREBASE_WEB_APP_ID',
        defaultValue: '1:935092313069:web:897de0204af606d618a5e4'),
    messagingSenderId: String.fromEnvironment('FIREBASE_WEB_MESSAGING_SENDER_ID',
        defaultValue: '935092313069'),
    projectId: String.fromEnvironment('FIREBASE_WEB_PROJECT_ID',
        defaultValue: 'shoplens-dev-499700'),
    storageBucket: String.fromEnvironment('FIREBASE_WEB_STORAGE_BUCKET',
        defaultValue: 'shoplens-dev-499700.firebasestorage.app'),
    authDomain: String.fromEnvironment('FIREBASE_WEB_AUTH_DOMAIN',
        defaultValue: 'shoplens-dev-499700.firebaseapp.com'),
    measurementId: 'G-BZDFBMKQFR',
  );
}
