// Generated by FlutterFire CLI (Android) + manually added web options from frontend/.env
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web; // fallback for Windows/macOS desktop dev
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDVt5Tb3NB28lxVosZeFc_-ZwQQUB9EE8',
    appId: '1:156370923364:android:5d1b87929bbdf0e970d471',
    messagingSenderId: '156370923364',
    projectId: 'shoplens-dev-prj',
    storageBucket: 'shoplens-dev-prj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv_sBKWIBoPC87E96IHeRo9Vm_vIWhxGM',
    appId: '1:156370923364:ios:8718b68dacda95b870d471',
    messagingSenderId: '156370923364',
    projectId: 'shoplens-dev-prj',
    storageBucket: 'shoplens-dev-prj.firebasestorage.app',
    iosClientId: '156370923364-q8093os77qubtesc4fsskm3sov82jes7.apps.googleusercontent.com',
    iosBundleId: 'com.shoplens.app',
  );

  // Defaults below are the dev Firebase project (shoplens-dev-prj),
  // used for local development and dev/preview builds. The prod build
  // overrides these via --dart-define in deploy-firebase.yml so the prod
  // Firebase Hosting site (shoplens-dev-prj) talks to the dev Firebase
  // project instead of dev.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY',
        defaultValue: 'AIzaSyASGt9vR3C2cr03BXAKjRrcDPPTqvwdcio'),
    appId: String.fromEnvironment('FIREBASE_WEB_APP_ID',
        defaultValue: '1:156370923364:web:253239fa549d313870d471'),
    messagingSenderId: String.fromEnvironment('FIREBASE_WEB_MESSAGING_SENDER_ID',
        defaultValue: '156370923364'),
    projectId: String.fromEnvironment('FIREBASE_WEB_PROJECT_ID',
        defaultValue: 'shoplens-dev-prj'),
    storageBucket: String.fromEnvironment('FIREBASE_WEB_STORAGE_BUCKET',
        defaultValue: 'shoplens-dev-prj.firebasestorage.app'),
    authDomain: String.fromEnvironment('FIREBASE_WEB_AUTH_DOMAIN',
        defaultValue: 'shoplens-dev-prj.firebaseapp.com'),
  );
}